version: "3"
services: 
  mongo:
    container_name: mongo-container 
    image: mongo:3
    restart: always
    volumes: 
      - ./Database:/data/db
    ports: 
      - "27017:27017"
  api: 
    container_name: 4devs-api-container
    restart: always
    working_dir: /usr/Source/4devs-api/Dist
    image: node:14
    command: bash -c "npm install --only=prod && npm run start:dev"
    environment: 
      - MONGO_URL=mongodb://mongo:27017/4devs-api
    volumes: 
      - ./Dist/:/usr/Source/4devs-api/Dist/
      - ./package.json:/usr/Source/4devs-api/package.json
    ports:
      - "3333:3333"
    links:
      - "mongo"